### ISSUE TITLE
Cannot install in node 10.3.0

### ISSUE THREAD

**Issue by wesleytodd** [Netflix-Skunkworks/spectator-js-nodejsmetrics#9]
```
$  node --version && npm --version && npm install nflx-spectator-nodejsmetrics@0.0.4
v10.3.0
6.1.0

> nflx-spectator-nodejsmetrics@0.0.4 install /__TEST/node_modules/nflx-spectator-nodejsmetrics
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/bin/node" "/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /__TEST/node_modules/nflx-spectator-nodejsmetrics
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nflx-spectator-nodejsmetrics@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nflx-spectator-nodejsmetrics@0.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2019-07-29T20_20_08_918Z-debug.log
```

Let me know if there is any more information which would help get this fixed.

**Comment by dmuino** [comment]
This is not related to this node module. My guess is that you'll have similar issues installing any binary node module. Doing a quick search for your error yields:

```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

as a possible solution.

**Comment by wesleytodd** [comment]
My assumption was that `AttributeError: 'NoneType' object has no attribute 'groups'` was the actual error and not the missing tools because I was successfully able to run the same command above after updating to node 10.16.2.  Also, before I opened this issue I found the same instructions, it did not make a difference.

Now that I am looking back on this, I think I agree it must have been something on my machine because this works:

```
docker run -it --rm --name test -v "$PWD":/usr/src/app -w /usr/src/app node:10.3.0 npm install nflx-spectator-nodejsmetrics@0.0.4
```

FWIW, the same try with node 12 is for sure broken:

```
docker run -it --rm --name test -v "$PWD":/usr/src/app -w /usr/src/app node:12 npm install nflx-spectator-nodejsmetrics

Unable to find image 'node:12' locally
12: Pulling from library/node
a4d8138d0f6b: Pull complete
dbdc36973392: Pull complete
f59d6d019dd5: Pull complete
aaef3e026258: Pull complete
6e454d3b6c28: Pull complete
c717a7c205aa: Pull complete
543d5a743e8e: Pull complete
5a2bc083aabd: Pull complete
ba44fd9296ef: Pull complete
Digest: sha256:be391e015ffcd5d21a879cb07614aa57873715c3bd742406394ffa9d221f726d
Status: Downloaded newer image for node:12

> nflx-spectator-nodejsmetrics@0.0.4 install /usr/src/app/node_modules/nflx-spectator-nodejsmetrics
> node-gyp rebuild

make: Entering directory '/usr/src/app/node_modules/nflx-spectator-nodejsmetrics/build'
  CXX(target) Release/obj.target/spectator_internals/internals/functions.o
../internals/functions.cc: In member function 'void DetailedHeapStats::serialize(v8::Local<v8::Object>)':
../internals/functions.cc:64:28: warning: 'bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
       heap_spaces->Set(i, h);
                            ^
In file included from /root/.cache/node-gyp/12.8.0/include/node/v8-internal.h:14:0,
                 from /root/.cache/node-gyp/12.8.0/include/node/v8.h:25,
                 from /root/.cache/node-gyp/12.8.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../internals/functions.cc:1:
/root/.cache/node-gyp/12.8.0/include/node/v8.h:3375:26: note: declared here
                     bool Set(uint32_t index, Local<Value> value));
                          ^
/root/.cache/node-gyp/12.8.0/include/node/v8config.h:326:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../internals/functions.cc: At global scope:
../internals/functions.cc:213:12: error: 'Handle' in namespace 'v8' does not name a template type
 static v8::Handle<v8::Value> max_fd_value() {
            ^~~~~~
../internals/functions.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE GetCurMaxFd(Nan::NAN_METHOD_ARGS_TYPE)':
../internals/functions.cc:245:69: warning: 'bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
   res->Set(Nan::New("used").ToLocalChecked(), Nan::New<Number>(used));
                                                                     ^
In file included from /root/.cache/node-gyp/12.8.0/include/node/v8-internal.h:14:0,
                 from /root/.cache/node-gyp/12.8.0/include/node/v8.h:25,
                 from /root/.cache/node-gyp/12.8.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../internals/functions.cc:1:
/root/.cache/node-gyp/12.8.0/include/node/v8.h:3366:26: note: declared here
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/root/.cache/node-gyp/12.8.0/include/node/v8config.h:326:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../internals/functions.cc:247:59: error: 'max_fd_value' was not declared in this scope
   res->Set(Nan::New("max").ToLocalChecked(), max_fd_value());
                                                           ^
spectator_internals.target.mk:121: recipe for target 'Release/obj.target/spectator_internals/internals/functions.o' failed
```

**Comment by dmuino** [comment]
FYI, node 12 now works as well using version 0.1.0.
